name: ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install libusb, libudev (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev libudev-dev

      - uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1.3.0

      - name: Build
        run: |
          cargo build --manifest-path teleprobe/Cargo.toml
          cargo build --manifest-path teleprobe/Cargo.toml --release
          cargo test --manifest-path teleprobe/Cargo.toml
          cargo test --manifest-path teleprobe/Cargo.toml --release
